function paredMaskArtery = functionGetSegment(z_projection_optical, interface_above, interface_below, xValids)

[hRegion,wRegion] = size(z_projection_optical);

interfacePolarAnterior = functionInterfaceToImg( interface_above , hRegion, wRegion);
maskAnterior = functionLabelizarPixelPolar( interfacePolarAnterior );

interfacePolarPosterior = functionInterfaceToImg( interface_below , hRegion, wRegion);
maskPosterior = functionLabelizarPixelPolar( interfacePolarPosterior );
paredMaskArtery = xor(maskAnterior,maskPosterior);

validoArteria = round(xValids(1)):1:round(xValids(2));

[meanPx, stdPx, imtPxMedia1, imtPxStd1, medicionesIMTmm1, imtPxMedian1,...
imtPxMedia2, imtPxStd2, medicionesIMTmm2, imtPxMedian2] =...
    functionThickness( interface_above(:,1),interface_above(:,2),interface_below(:,1),...
    interface_below(:,2),validoArteria,paredMaskArtery, 1 );


strStatistics = {strcat('Distance px Mean: ',num2str(meanPx)),...
    strcat('Distance px Std: ',num2str(stdPx)),...
    strcat('-------------','----'),...
    strcat('Distance px Mean 1: ',num2str(imtPxMedia1)),...
    strcat('Distance px Std 1: ',num2str(imtPxStd1)),...
    strcat('Distance px Median 1: ',num2str(imtPxMedian1))...
    strcat('Number of measurements 1: ',num2str(medicionesIMTmm1)),...
    strcat('-------------','----'),...
    strcat('Distance px Media 2: ',num2str(imtPxMedia2)),...
    strcat('Distance px Std 2: ',num2str(imtPxStd2)),...
    strcat('Distance px Median 2: ',num2str(imtPxMedian2))...
    strcat('Number of measurements 2: ',num2str(medicionesIMTmm2)),...
    strcat('-------------------------------------------'),...
    };

conSaltoDeLinea = strjoin(strStatistics,'\n');

disp(conSaltoDeLinea);

end

