function [strStatisticsExpression, matrixCSV, headersCSV] =...
    functionStatsProfiles(list_max,list_negative_first_gradient,...
    list_negative_first_gradient_pos_px,list_negative_first_gradient_pos_real,list_length_px,list_length_real)


strStatisticsExpression = {'',...
    '---Expression----',...
'median max',...
num2str(median(list_max)),...
'median neg gradient',...
num2str(median(list_negative_first_gradient)),...
'median pos neg gradient px',...
num2str(median(list_negative_first_gradient_pos_px)),...
'median pos neg gradient real',...
num2str(median(list_negative_first_gradient_pos_real)),...
'median list_length px',...
num2str(median(list_length_px)),...
'-------------',...
'mean max',...
num2str(mean(list_max)),...
'mean neg gradient',...
num2str(mean(list_negative_first_gradient)),...
'mean pos neg gradient px',...
num2str(mean(list_negative_first_gradient_pos_px)),...
'mean pos neg gradient real',...
num2str(mean(list_negative_first_gradient_pos_real)),...
'mean list_length px',...
num2str(mean(list_length_px))};

strStatisticsExpression = strjoin(strStatisticsExpression,'\n');

matrixCSV = [list_length_px',list_length_real',list_max',list_negative_first_gradient',...
    list_negative_first_gradient_pos_px',list_negative_first_gradient_pos_real'];
headersCSV = {'length_px','length_real','max_profile','negative_first_gradient',...
    'negative_first_gradient_pos_px','negative_first_gradient_pos_real'};
end

