function [paredMaskArtery, strStatisticsGeometry, meanPx, meanIMTReal] = functionGetSegment(z_projection_optical, interface_above, interface_below, xValids, mmpx)

[hRegion,wRegion] = size(z_projection_optical);

interfacePolarAnterior = functionInterfaceToImg( interface_above , hRegion, wRegion);
maskAnterior = functionLabelizarPixelPolar( interfacePolarAnterior );

interfacePolarPosterior = functionInterfaceToImg( interface_below , hRegion, wRegion);
maskPosterior = functionLabelizarPixelPolar( interfacePolarPosterior );
paredMaskArtery = xor(maskAnterior,maskPosterior);

paredMaskArtery=imdilate(paredMaskArtery, ones(2,2));

validoArteria = round(xValids(1)):1:round(xValids(2));

[meanPx, stdPx, imtPxMedia1, imtPxStd1, medicionesIMTmm1, imtPxMedian1,...
imtPxMedia2, imtPxStd2, medicionesIMTmm2, imtPxMedian2, meanIMTReal, stdIMTReal] =...
    functionThickness( interface_above(:,1),interface_above(:,2),interface_below(:,1), interface_below(:,2),validoArteria,paredMaskArtery, mmpx );

%debug
%figure, imshow(paredMaskArtery);

strStatisticsGeometry = {'----Geometry-----',...
    'Distance px Mean: ',num2str(meanPx),...
    'Distance px Std: ',num2str(stdPx),...
    '-------------',...
    'Distance Real Mean: ',num2str(meanIMTReal),...
    'Distance Real Std: ',num2str(stdIMTReal),...
    '-------------',...
    'Distance px Mean 1: ',num2str(imtPxMedia1),...
    'Distance px Std 1: ',num2str(imtPxStd1),...
    'Distance px Median 1: ',num2str(imtPxMedian1),...
    'Number of measurements 1: ',num2str(medicionesIMTmm1),...
    '-------------',...
    'Distance px Media 2: ',num2str(imtPxMedia2),...
    'Distance px Std 2: ',num2str(imtPxStd2),...
    'Distance px Median 2: ',num2str(imtPxMedian2),...
    'Number of measurements 2: ',num2str(medicionesIMTmm2),...
    '-------------------------------------------'};

strStatisticsGeometry = strjoin(strStatisticsGeometry,'\n');

%disp(withLineBreak);

end

